### ISSUE TITLE
Question #12: What is the purpose of callback function as an argument of setState()?

### ISSUE THREAD

**Issue by amelinium23** [sudheerj/reactjs-interview-questions#205]
I think, that we can't say that: `setState` is asynchronous function. It's is **synchronous** and only `render` method is asynchronous. 

This issue is described in various tutorials and even in [react repo](https://github.com/facebook/react/blob/main/packages/react/src/ReactHooks.js#L100) that is synchronous.

Please changed it because it is very confusing and not true at all.

**Comment by amelinium23** [comment]
There is a [one](https://youtu.be/RAJD4KpX8LA)

**Comment by chetannada** [comment]
Hi @amelinium23 `setState()` is asynchronous function. 
ReactJs sets its state `asynchronously` because it can result in an `expensive operation`. Making it `synchronous` might leave the `browser unresponsive`. `Asynchronous setState` calls are batched to provide a `better user experience and performance`.

The setState function takes an `optional callback parameter` that can be used to `make updates after the state is changed`.
```
this.setState({ value: e.target.value }, () =>
  console.log('Final value:- ', this.state.value)
);
```
This function will get `called once the state has been updated`, and the `callback will receive the updated value of the state`.

For more `Reference` check [GeeksforGeeks tutorial](https://www.geeksforgeeks.org/is-setstate-method-async/)

@sudheerj You should `close this issue` after checking above [GeeksforGeeks tutorial](https://www.geeksforgeeks.org/is-setstate-method-async/)

**Comment by Leen-odeh12** [comment]
Useful comment
